base/urls.py
from django.urls import path
from . import views

app_name = "base" 

urlpatterns = [
    path("home/", views.home, name="home"),
    path("patientinfo/<str:entry>", views.patientinfo, name="patientinfo"),
    path("upload/", views.upload, name="upload"),
    path("monthly/", views.monthly, name="monthly"),
    path("calendar/", views.calendar, name="calendar"),
    path("register/", views.register_request, name="register"),
    path("", views.login_request, name="login"),
    path("searchpatient/", views.searchpatient,name="searchpatient")
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('base.urls')),
]

templates/calendar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Bootstrap 5 Admin &amp; Dashboard Template">
	<meta name="author" content="Bootlab">

	<title>InManage - Inpatient Rehabilitation Management</title>

	<link rel="canonical" href="https://appstack.bootlab.io/calendar.html" />
	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">

	<link href="{% static 'css/light.css' %}" rel="stylesheet">
</head>
<!--
  HOW TO USE: 
  data-theme: default (default), dark, light
  data-layout: fluid (default), boxed
  data-sidebar-position: left (default), right
  data-sidebar-behavior: sticky (default), fixed, compact
-->

<body data-theme="default" data-layout="fluid" data-sidebar-position="left" data-sidebar-behavior="sticky">
	<div class="wrapper">
	{% include 'navbar.html' %}
		<div class="main">
			{% include 'header.html' %}			
			<main class="content">
				<div class="container-fluid p-0">

					<h1 class="h3 mb-3">Calendar</h1>

					<div class="card">
						<div class="card-header">
							<h5 class="card-title">Patient Admission Calendar</h5>
						</div>
						<div class="card-body">
							<div id="fullcalendar"></div>
						</div>
					</div>

				</div>
			</main>
			{% include 'footer.html' %}
		</div>
	</div>

	<script src="{% static 'js/app.js' %}"></script>

	<script>
		document.addEventListener("DOMContentLoaded", function() {
			var calendarEl = document.getElementById('fullcalendar');
			var calendar = new FullCalendar.Calendar(calendarEl, {
				themeSystem: 'bootstrap',
				initialView: 'dayGridMonth',
				initialDate: '2022-10-20',
				headerToolbar: {
					left: 'prev,next today',
					center: 'title',
					right: 'dayGridMonth,timeGridWeek,timeGridDay'
				},
				events: [
				]
			});
			setTimeout(function() {
				calendar.render();
			}, 250)
		});
	</script>
</body>

</html>

templates/footer.html
<footer class="footer">
	<div class="container-fluid">
		<div class="row text-muted">
			<div class="col-6 text-start">
				<ul class="list-inline">
					<li class="list-inline-item">
						<a class="text-muted" href="#">Support</a>
					</li>
					<li class="list-inline-item">
						<a class="text-muted" href="#">Help Center</a>
					</li>
					<li class="list-inline-item">
						<a class="text-muted" href="#">Privacy</a>
					</li>
					<li class="list-inline-item">
						<a class="text-muted" href="#">Terms of Service</a>
					</li>
				</ul>
			</div>
			<div class="col-6 text-end">
				<p class="mb-0">
					&copy; 2022 - <a href="index.html" class="text-muted">AppStack</a>
				</p>
			</div>
		</div>
	</div>
</footer>

templates/header.html
<nav class="navbar navbar-expand navbar-light navbar-bg">
	<a class="sidebar-toggle">
<i class="hamburger align-self-center"></i>
</a>

	<form class="d-none d-sm-inline-block">
		<div class="input-group input-group-navbar">
			<input type="text" class="form-control" placeholder="Search patients…" aria-label="Search">
			<button class="btn" type="button">
  <i class="align-middle" data-feather="search"></i>
</button>
		</div>
	</form>


	<div class="navbar-collapse collapse">
		<ul class="navbar-nav navbar-align">
			<li class="nav-item dropdown">
				<a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
					<i class="align-middle" data-feather="settings"></i>
				</a>

				<a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
					<span class="text-dark">Abhi Prasad</span>
				</a>
				<div class="dropdown-menu dropdown-menu-end">
					<a class="dropdown-item" href="pages-profile.html"><i class="align-middle me-1" data-feather="user"></i> Profile</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="/">Sign out</a>
				</div>
			</li>
		</ul>
	</div>
</nav>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Bootstrap 5 Admin &amp; Dashboard Template">
	<meta name="author" content="Bootlab">

	<title>InManage - Inpatient Rehabilitation Management</title>

	<link rel="canonical" href="https://appstack.bootlab.io/dashboard-default.html" />
	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">

	<!-- Choose your prefered color scheme -->
	<link href="{% static 'css/light.css' %}" rel="stylesheet">
	<!-- <link href="css/dark.css" rel="stylesheet"> -->

</head>

<body data-theme="default" data-layout="fluid" data-sidebar-position="left" data-sidebar-behavior="sticky">
	<div class="wrapper">
	{% include 'navbar.html' %}
		<div class="main">
			{% include 'header.html' %}
			<main class="content">
				<div class="container-fluid p-0">

					<div class="row mb-2 mb-xl-3">
						<div class="col-auto d-none d-sm-block">
							<h3>Main Dashboard</h3>
						</div>

						<div class="col-auto ms-auto text-end mt-n1">

							<button class="btn btn-primary shadow-sm">
							  <i class="align-middle" data-feather="filter">&nbsp;</i>
							</button>
													<button class="btn btn-primary shadow-sm">
							  <i class="align-middle" data-feather="refresh-cw">&nbsp;</i>
							</button>
						</div>
					</div>
					<div class="row">
						<div class="col-12 col-sm-6 col-xxl-3 d-flex">
							<div class="card illustration flex-fill">
								<div class="card-body p-0 d-flex flex-fill">
									<div class="row g-0 w-100">
										<div class="col-6">
											<div class="illustration-text p-3 m-1">
												<h4 class="illustration-text">Welcome Back!</h4>
												<p class="mb-0">Admissions Manager</p>
											</div>
										</div>
										<div class="col-6 align-self-end text-end">
											<img src="{% static 'img/illustrations/customer-support.png' %}" alt="Customer Support" class="img-fluid illustration-img">
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-12 col-sm-6 col-xxl-3 d-flex">
							<div class="card flex-fill">
								<div class="card-body py-4">
									<div class="d-flex align-items-center">
										<div class="flex-grow-1">
											<h3 class="mb-2">Number of Beds Occupied</h3>
											<div class="row">
												<div class="d-flex align-items-center">
													<span class="h1 d-inline-block mt-1 mb-4 margin:auto">{{accepted}}/40</span>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
	
						<div class="col-12 col-sm-6 col-xxl-3 d-flex">
							<div class="card flex-fill">
								<div class="card-body py-4">
									<div class="d-flex align-items-start">
										<div class="flex-grow-1">
											<h3 class="mb-2">CMS 60% Rule Requirement</h3>
											<p class="mb-2">Number of Patients meeting criteria</p>
											<span class="h1 d-inline-block mt-1 mb-4">{{cms_percent}}%</span>
										</div>
										<div class="d-inline-block ms-3">
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-12 col-sm-6 col-xxl-3 d-flex">
							<div class="card">
								<div class="card-header">
									<div class="d-flex align-items-start">
										<h3 class="mb-2">Patient Status Breakdown</h3>
									</div>
								<div class="card-body text-center">
									<div class="chart-m">
										<div id="statusPIE" style="max-width: 440px;margin:auto;"></div>
									</div>
								</div>
							</div>
						</div>
						
					</div>
					

					<div class="card flex-fill">
						<div class="card-header">
							<div class="card-actions float-end">
								<div class="dropdown position-relative">
									<a href="#" data-bs-toggle="dropdown" data-bs-display="static">
          <i class="align-middle" data-feather="more-horizontal"></i>
        </a>

				
								</div>
							</div>
							<h5 class="card-title mb-0">Patient Summary</h5>
						</div>
						<table id="datatables-dashboard-projects" class="table table-striped my-0">
							<thead>
								<tr>
									<th>Patient Name</th>
									<th class="d-none d-xl-table-cell">Diagnosis</th>
									<th class="d-none d-xl-table-cell">Referral Date</th>
									<th class = "d-none d-md-table-cell">Status</th>
									<th class="d-none d-md-table-cell">Assignee</th>
								</tr>
							</thead>
							<tbody>
								{% for entry in patients %}
								<tr>	
									<td><a href="{% url 'base:patientinfo' entry.patientname %}">{{entry.patientname}}</a></td>
									<td class="d-none d-xl-table-cell">{{entry.Diagnosis}}</td>
									<td class="d-none d-xl-table-cell">{{entry.ReferralDate}}</td>
									<td><span class="d-none d-md-table-cell">{{entry.Status}}</span></td>
									<td class="d-none d-md-table-cell">{{entry.Assignee}}</td>
								</tr>
								{%endfor%}
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</main>
			{% include 'footer.html' %}
		</div>
	</div>

	<script src="{% static 'js/app.js' %}"></script>

	<script>
		document.addEventListener("DOMContentLoaded", function() {
			$("#datetimepicker-dashboard").datetimepicker({
				inline: true,
				sideBySide: false,
				format: "L"
			});
		});
	</script>
	<script>
		document.addEventListener("DOMContentLoaded", function() {
		// Pie chart
		var options = {
		chart: {
		height: 350,
		type: "pie",
		},
		dataLabels: {
		enabled: false
		},
		Style: {
		
		},
		labels: ["Accepted","Rejected","Pending"],
		colors: ["#32CD32","#FF0000","#FFA500"],
		series: [{{accepted}},{{rejected}},{{pending}}]
		}
		var chart = new ApexCharts(
		document.querySelector("#statusPIE"),
		options
		);
		chart.render();
		});
		</script>
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			// Doughnut chart
			new Chart(document.getElementById("chartjs-doughnut"), {
				type: "doughnut",
				data: {
					labels: ["Social", "Search Engines", "Direct", "Other"],
					datasets: [{
						data: [260, 125, 54, 146],
						backgroundColor: [
							window.theme.primary,
							window.theme.success,
							window.theme.warning,
							"#E8EAED"
						],
						borderColor: "transparent"
					}]
				},
				options: {
					maintainAspectRatio: false,
					cutoutPercentage: 65,
					legend: {
						display: false
					}
				}
			});
		});
	</script>
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			$("#datatables-dashboard-projects").DataTable({
				pageLength: 6,
				lengthChange: false,
				bFilter: false,
				autoWidth: false
			});
		});
	</script>

</body>

</html>

templates/monthly.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Bootstrap 5 Admin &amp; Dashboard Template">
	<meta name="author" content="Bootlab">

	<title>InManage - Inpatient Rehabilitation Management</title>

	<link rel="canonical" href="https://appstack.bootlab.io/dashboard-default.html" />
	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">

	<!-- Choose your prefered color scheme -->
	<link href="{% static 'css/light.css' %}" rel="stylesheet">
	<!-- <link href="css/dark.css" rel="stylesheet"> -->

</head>

<body data-theme="default" data-layout="fluid" data-sidebar-position="left" data-sidebar-behavior="sticky">
	<div class="wrapper">
	{% include 'navbar.html' %}
	<div class="main">
		{% include 'header.html' %}
		<main class="content">


		<div class="row">
			<div class="container-fluid p-0">
				<div class="row">
					<div class="col">
						<div class="card flex-fill">
							<div class="card-body">
								<div class="row">
									<div class="col mt-0">
										<h4 class="card-title">CMS 60% Rule Requirement</h4>
									</div>
									<div class="col-auto">
										<div class="stat stat-sm">
											<i class="align-middle" data-feather="activity"></i>
										</div>
									</div>
								</div>
								<span class="h1 d-inline-block mt-1 mb-4">{{cms_percent}} %</span>
							</div>
						</div>
					</div>
					<div class="col">
						<div class="flex-grow-1">
						<div class="card flex-fill">
							<div class="card-body">
								<div class="row">
									<div class="col mt-0">
										<h4 class="card-title">Percentage of Patient Beds Full</h4>
									</div>
									<div class="col-auto">
										<div class="stat stat-sm">
											<i class="align-middle" data-feather="users"></i>
										</div>
									</div>
								</div>
								<span class="h1 d-inline-block mt-1 mb-4">{{bed_percent}} %</span>
							</div>
						</div>
						</div>
					</div>
				</div>
		
			<div class="container-fluid p-0">
				<div class="row">
					<div class="col">
						<div class="card">
							<div class="card-header">
								<h5 class="card-title">Patient Status Breakdown</h5>
								<h6 class="card-subtitle text-muted">Breakdown of current status of patients</h6>
							</div>
						<div class="card-body text-center">
							<div class="chart">
								<div id="statusPIE" style="max-width: 340px;margin:auto;"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-12 col-lg-6">
					<div class="card">
						<div class="card-header">
							<h5 class="card-title">Disposition Breakdown </h5>
							<h6 class="card-subtitle text-muted">Breakdown of reasons for patient rejections</h6>
						</div>
						<div class="card-body text-center">
							<div class="chart w-100">
								<div id="RejectionDisposition" style="max-width: 440px;margin:auto;"></div>
							</div>
						</div>
					</div>
					</div>
				</div>
			<div class="container-fluid p-0">
				<div class="card">
					<div class="card-header">
						<h4 class="card-title">Insurance Breakdown</h4>
						<h6 class="card-subtitle text-muted"></h6>Breakdown of most used insurances</h6>
					</div>
					<div class="card-body text-center">
						<div class="chart w-100">
							<div id="InsurancePIE" style="max-width: 440px;margin:auto;"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
			<div class="card">
				<div class="card-header">
						<h5 class="card-title">Referral Hospital Breakdown</h5>
						<h6 class="card-subtitle text-muted">Breakdown of local hospitals' patient referral</h6>
					</div>
					<div class="card-body">
						<div class="card flex-fill">
							<div id="apexcharts-bar"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
		</main>
		{% include 'footer.html' %}
	</div>
</div>

	<script src="{% static 'js/app.js' %}"></script>

	<script>
	document.addEventListener("DOMContentLoaded", function() {
	///////////////////// Bar chart Referral Hosptial Breakdown
	var options = {
	chart: {
	height: 350,
	type: "bar",
	stacked: true,
	},
	plotOptions: {
	bar: {
	horizontal: true,
	},
	},
	stroke: {
	width: 1,
	colors: ["#fff"]
	},
	series: [{
	name: "Number of Rejections",
	data: [{{hospitalIUr}}, {{FranEastr}}, {{FranCentralr}},{{other_refr}}]
	}, {
	name: "Number of Acceptances",
	data: [{{hospitalIUa}}, {{FranEasta}}, {{FranCentrala}},{{other_refa}}]
	},{
	name: "Number of CMS 13 Pateints",
	data: [{{hospitalIUc}},{{FranEastc}}, {{FranCentralc}},{{other_refc}}]
	} ],
	xaxis: {
	categories: ['IU Health Arnett Hospital', 'Franciscan Health Lafayette East', 'Fransciscan Health Lafayette Central',"Other"],
	labels: {
	formatter: function(val) {
	return val
	}
	}
	},
	yaxis: {
	title: {
	text: 'Hospital'
	},
	},
	tooltip: {
	y: {
	formatter: function(val) {
	return val
	}
	}
	},
	fill: {
	opacity: 1
	},
	legend: {
	position: "top",
	horizontalAlign: "left",
	offsetX: 40
	}
	}
	var chart = new ApexCharts(
	document.querySelector("#apexcharts-bar"),
	options
	);
	chart.render();
	});
	document.addEventListener("DOMContentLoaded", function() {
	////////////////////// Bar chart Referring Physician
	var options = {
	chart: {
	height: 350,
	type: "bar",
	stacked: true,
	},
	plotOptions: {
	bar: {
	horizontal: true,
	},
	},
	stroke: {
	width: 1,
	colors: ["#fff"]
	},
	series: [{
	name: "Doctor 1",
	data: [44, 55, 41, 37, 22, 43, 21]
	}, {
	name: "Doctor 2",
	data: [12, 17, 11, 9, 15, 11, 20]
	},{
	name: "Doctor 3",
	data: [53, 32, 33, 52, 13, 43, 32]
	}, {
	name: "Doctor 4",
	data: [9, 7, 5, 8, 6, 9, 4]
	}, ],
	xaxis: {
	categories: ['IU Health Arnett Hospital', 'IU Health Arnett', 'Franciscan Health Lafayette East', 'Fransciscan Health Lafayette Central'],
	labels: {
	formatter: function(val) {
	return val
	}
	}
	},
	yaxis: {
	title: {
	text: undefined
	},
	},
	tooltip: {
	y: {
	formatter: function(val) {
	return val
	}
	}
	},
	fill: {
	opacity: 1
	},
	legend: {
	position: "top",
	horizontalAlign: "left",
	offsetX: 40
	}
	}
	var chart = new ApexCharts(
	document.querySelector("#ReferringPhysician-bar"),
	options
	);
	chart.render();
	});
	</script>
	<script>
	document.addEventListener("DOMContentLoaded", function() {
	// Pie chart
	var options = {
    chart: {
    height: 650,
    type: "pie",
    },
    dataLabels: {
    enabled: true
    },
	labels: ["Anthem","United Healthcare","Medicaid","Blue Cross", "Other"],
    series: [{{insur_anthem}},{{insur_UHC}},{{insur_medicaid}},{{insur_blue}},{{insur_other}}],
    }
    var chart = new ApexCharts(
    document.querySelector("#InsurancePIE"),
    options
    );
    chart.render();
    });
    </script>

	<script>
	document.addEventListener("DOMContentLoaded", function() {
	// Pie chart
	var options = {
	chart: {
	height: 350,
	type: "pie",
	},
	dataLabels: {
	enabled: false
	},
	Style: {
	
	},
	labels: ["Accepted","Rejected","Pending"],
	colors: ["#32CD32","#FF0000","#FFA500"],
	series: [{{accepted}},{{rejected}},{{pending}}]
	}
	var chart = new ApexCharts(
	document.querySelector("#statusPIE"),
	options
	);
	chart.render();
	});
	</script>


	<script>
	/////////////////////// Disposition Pie Chart///////////////////
	document.addEventListener("DOMContentLoaded", function() {
		var options = {
	chart: {
	height: 650,
	type: "donut",
	},
	dataLabels: {
	enabled: true
	},
	labels:["Not CMS qalified","Insurance denial","Not qualified for inpatient","Other"],
	series: [{{reason1}},{{reason2}},{{reason3}},{{reasonother}}]
	}
	var chart = new ApexCharts(
	document.querySelector("#RejectionDisposition"),
	options
	);
	chart.render();
	});
	</script>
</a>

</script>

</body>




</html>

templates/navbar.html
<nav id="sidebar" class="sidebar">
	<div class="sidebar-content js-simplebar">
		<a class="sidebar-brand" href="/home">
  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	width="20px" height="20px" viewBox="0 0 20 20" enable-background="new 0 0 20 20" xml:space="preserve">
	<path d="M19.4,4.1l-9-4C10.1,0,9.9,0,9.6,0.1l-9,4C0.2,4.2,0,4.6,0,5s0.2,0.8,0.6,0.9l9,4C9.7,10,9.9,10,10,10s0.3,0,0.4-0.1l9-4
	  C19.8,5.8,20,5.4,20,5S19.8,4.2,19.4,4.1z"/>
	<path d="M10,15c-0.1,0-0.3,0-0.4-0.1l-9-4c-0.5-0.2-0.7-0.8-0.5-1.3c0.2-0.5,0.8-0.7,1.3-0.5l8.6,3.8l8.6-3.8c0.5-0.2,1.1,0,1.3,0.5
	  c0.2,0.5,0,1.1-0.5,1.3l-9,4C10.3,15,10.1,15,10,15z"/>
	<path d="M10,20c-0.1,0-0.3,0-0.4-0.1l-9-4c-0.5-0.2-0.7-0.8-0.5-1.3c0.2-0.5,0.8-0.7,1.3-0.5l8.6,3.8l8.6-3.8c0.5-0.2,1.1,0,1.3,0.5
	  c0.2,0.5,0,1.1-0.5,1.3l-9,4C10.3,20,10.1,20,10,20z"/>
  </svg>

  <span class="align-middle me-3">InManage</span>
</a>

		<ul class="sidebar-nav">
			<li class="sidebar-header">
				Pages
			</li>

			<li class="sidebar-item">
				<a class="sidebar-link" href="/searchpatient">
	  <i class="align-middle" data-feather="users"></i> <span class="align-middle">Add Patient</span>
	</a>
			</li>
			
			<li class="sidebar-item">
				<a class="sidebar-link" href="/upload">
	  <i class="align-middle" data-feather="users"></i> <span class="align-middle">Upload Patient Record</span>
	</a>
			</li>
			
			<li class="sidebar-item">
				<a class="sidebar-link" href="/monthly">
	  <i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Monthly Analytics</span>
	</a>
			</li>

			<li class="sidebar-item">
				<a class="sidebar-link" href="/calendar">
	  <i class="align-middle" data-feather="calendar"></i> <span class="align-middle">Calendar</span>
	</a>
			</li>
		</ul>
	</div>
</nav>

templates/upload.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Bootstrap 5 Admin &amp; Dashboard Template">
	<meta name="author" content="Bootlab">

	<title>InManage - Inpatient Rehabilitation Management</title>

	<link rel="canonical" href="https://appstack.bootlab.io/dashboard-default.html" />
	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">

	<!-- Choose your prefered color scheme -->
	<link href="{% static 'css/light.css' %}" rel="stylesheet">
	<!-- <link href="css/dark.css" rel="stylesheet"> -->

</head>

<body data-theme="default" data-layout="fluid" data-sidebar-position="left" data-sidebar-behavior="sticky">
	<div class="wrapper">
	{% include 'navbar.html' %}
		<div class="main">
			{% include 'header.html' %}
			<main class="content">
				<div class="container-fluid p-0">
					<div class="col-sm-6 col-lg-12 col-xxl-6 d-flex">
						<div class="card flex-fill">
							<div class="card-body">
							<h1 class="h1 d-inline-block mt-1 mb-4">Upload Patient Record</h1>
								<form method="post" enctype="multipart/form-data">
									{% csrf_token %}
									<label class="form-label"><strong>Patient Record (Must be .pdf format)<strong></label>
									<div>
										<input type="file" name="patientfile">
									</div>
									<hr>
									<button type="submit" class="btn btn-primary" name="runscript">Submit</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</main>
			{% include 'footer.html' %}
		</div>
	</div>
	
	<script src="{% static 'js/app.js' %}"></script>

	<script>
	$(document).ready(function(){

	$("#b1").click(function(){

	$.ajax({

	method: "GET",

	url: "type your python script path here",

	data: {"place" : value},

	dataType: "text",

	success: function(result){

	var data=JSON.parse(result);

	console.log(result);

	}

	});

	});
	</script>

</body>

</html>